app = "rr-perf"  # Change this if you want a different app name
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "python:3.11-slim"

[env]
  TELEGRAM_TOKEN = ""  # We'll set this as a secret, leave blank here

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "python rr.py"
